---
# GitHub client secret sealed secret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secret
  namespace: circleci-server
spec:
  encryptedData:
    clientId: AgAJIhgQUzA+vB/wbBXfLn+ZttR10zDi/QaaBfw0rDGkFheMYR593QBGfnP7lEVdtP+eUy5U0hc82w1/3bnGRKw71UmQct0hV5OWt/CnYyNW7X63bSRpoDL5zdCEzXF41onVkBg1XzQGkwbbJNWrAaaX3equfJqjjQ6yhEastRiDNQIps690+iKDtNsPZwIrn6LsnngESTTIQ6eQApUyBxSJZh/Y12ZyEcdG8ZzIXpAt3Let1xK3qkeyEWbRmaxWPvUmCJHBZccehCBo599Ras0C5lQTEeVXKBjmStHjdstibAt8EMB/dWBeckOktZYBhJHEB4366E7rS4BckB2cGWxFAGlb9Svz55NU5/nyS6wur/izzaM6zLFzzwvYa8+I+JvNW2ljCIMhc00mx87IutmHuVE19+xbWSu+6dsqCgExbUnQ6Jp2dBqDeB4JhzJJBjVmWNOM9yIHJi7QHwAzwiz7WD3v29T4gE2bM8/uKF3GSIBqKgJ79WsjZFO0jd6VVKd/LwMrpeJKiyYZOo5Ahf7yzmevmQXxkY4h45RGJGYkllS9UeRp71B1iFjUaXXQhS90sAuOb0Xjyj88HGV2YZFt0+EZQPndbekviTCMhFxPXu+sYuQF15e8HBzUChQbeHyzDUqyaPoxG4UauVsydUKAamm3X/pBBolXppHLFmIyKDMkCg9cYmTCatoN3k7ECAdfuIfU8UMV1sYro+xJN3ULRpbJYw==
    clientSecret: AgDIn1M4UI6hFGUwdWdXTHHgTe6k0RZDTamgF5OUAh6MQoH9NYjai7IX/QKev8QVTx9UvAAjSADv+0/JFZNACmSthua/3cqDTIpOtk5lIhHx7JOEpYuQl20j6NNA9fKQryjJ9kSNVJ1jWJO+UT0MqU2ZCspOqE42g82HaBsIkc+k0vLFnYVksSeC/ub9pqD9eIIDLojtKrqUu+FpNA7ZyBLYaPwJ0oz9SaRV+YJXypXxyQdftgktqymz3uCcYT8aVFYiJYYnSy+h7T5Q5wdYj8lRqZ064UntLH2HHRF1vOe/M/avzJlrsyHDa1PQAGA7xkKxCZVvQYXlc3Be7HmAku56gsLH2mgPluPDWmgAoM/qPS3LQoiYhooghad61x403MYoRd4xRwAS5h5PkUxSv0F9vvWImIlAxIbM8S71emFD7HMrFkon7KX3726BA3wyLV/JSbF+pXdcVQsFKO4NDZkgH2GKLpxNA1TypMs1UDsOlwN8rMsxTng5Ty/mdHj8HKi/BTTbAJRXEPvC8llp9FXcuh/v41vvhNtQF/IIAEUeBLmheJwNaSD6EiH3HEmZ1mrnY17emU3vzb9bKXQjmRFKvL3bvRqDr0EbgacKwvGGeSFSHnOx6Aj15fQSWU9gHvHbQ0XAuxV11YKWmjMPZ9HXa+fy2CDsR3gd9tAPn7kPvTEnOmwd9w9mMEkvjzPfcMfBUBdAYLEhrnnq4DFB1YeIKc0nrdTiaCuq+mLrKqTxX+kTjHWP03Tu
  template:
    metadata:
      name: github-secret
      namespace: circleci-server
    type: Opaque
